namespace :db_seeder do
  desc "Populate Database with States"
  task state: :environment do
  	puts "#{'*'*(`tput cols`.to_i)}\nChecking Environment... The database will be cleared of all content before populating.\n#{'*'*(`tput cols`.to_i)}"

  	#delete state and run migration
  	#SET foreign_key_checks = 0;
  	#SET foreign_key_checks = 1;
  	# ActiveRecord::Base.connection.execute('SET foreign_key_checks = 0')
  	#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  	# ActiveRecord::Migration.drop_table(:states)
  	# ActiveRecord::Migration.drop_table(:local_govt_areas)
  	# ActiveRecord::Migration.drop_table(:schema_migrations)
  	#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  	# ActiveRecord::Base.connection.execute('SET foreign_key_checks = 1')
  	Rake::Task["db:migrate"].execute

	[
		{:state => "Abia"}, 
		{:state => "Adamawa"}, 
		{:state => "Akwa Ibom"}, 
		{:state => "Anambra"}, 
		{:state => "Bauchi"}, 
		{:state => "Bayelsa"}, 
		{:state => "Benue"}, 
		{:state => "Borno"}, 
		{:state => "Cross River"}, 
		{:state => "Delta"}, 
		{:state => "Ebonyi"}, 
		{:state => "Edo"}, 
		{:state => "Ekiti"}, 
		{:state => "Enugu"}, 
		{:state => "Abuja (FCT)"}, 
		{:state => "Gombe"}, 
		{:state => "Imo"}, 
		{:state => "Jigawa"}, 
		{:state => "Kaduna"}, 
		{:state => "Kano"}, 
		{:state => "Katsina"}, 
		{:state => "Kebbi"}, 
		{:state => "Kogi"}, 
		{:state => "Kwara"}, 
		{:state => "Lagos"}, 
		{:state => "Nasarawa"}, 
		{:state => "Niger"}, 
		{:state => "Ogun"}, 
		{:state => "Ondo"}, 
		{:state => "Osun"}, 
		{:state => "Oyo"}, 
		{:state => "Plateau"}, 
		{:state => "Rivers"}, 
		{:state => "Sokoto"}, 
		{:state => "Taraba"}, 
		{:state => "Yobe"}, 
		{:state => "Zamfara"}
		].each do |attributes|
			State.create(attributes)
		end

		puts "#{'*'*(`tput cols`.to_i)}\nThe database has been populated!\n#{'*'*(`tput cols`.to_i)}"

		Rake::Task["db_seeder:lga"].execute

  end

  desc "Populate Database with Local Govt. Area"
  task lga: :environment do
  	puts "#{'*'*(`tput cols`.to_i)}\nChecking Environment... The database will be cleared of all content before populating.\n#{'*'*(`tput cols`.to_i)}"

[
	{:state_id =>"1",:lga =>"Aba North"}, 
	{:state_id =>"1",:lga =>"Aba South"}, 
	{:state_id =>"1",:lga =>"Arochukwu"}, 
	{:state_id =>"1",:lga =>"Bende"}, 
	{:state_id =>"1",:lga =>"Ikwuano"}, 
	{:state_id =>"1",:lga =>"Isiala-Ngwa North"}, 
	{:state_id =>"1",:lga =>"Isiala-Ngwa South"}, 
	{:state_id =>"1",:lga =>"Isuikwato"}, 
	{:state_id =>"1",:lga =>"Obi Nwa"}, 
	{:state_id =>"1",:lga =>"Ohafia"}, 
	{:state_id =>"1",:lga =>"Osisioma"}, 
	{:state_id =>"1",:lga =>"Ngwa"}, 
	{:state_id =>"1",:lga =>"Ugwunagbo"}, 
	{:state_id =>"1",:lga =>"Ukwa East"}, 
	{:state_id =>"1",:lga =>"Ukwa West"}, 
	{:state_id =>"1",:lga =>"Umuahia North"}, 
	{:state_id =>"1",:lga =>"Umuahia South"}, 
	{:state_id =>"1",:lga =>"Umu-Neochi"}, 
	{:state_id =>"2",:lga =>"Demsa"}, 
	{:state_id =>"2",:lga =>"Fufore"}, 
	{:state_id =>"2",:lga =>"Ganaye"}, 
	{:state_id =>"2",:lga =>"Gireri"}, 
	{:state_id =>"2",:lga =>"Gombi"}, 
	{:state_id =>"2",:lga =>"Guyuk"}, 
	{:state_id =>"2",:lga =>"Hong"}, 
	{:state_id =>"2",:lga =>"Jada"}, 
	{:state_id =>"2",:lga =>"Lamurde"}, 
	{:state_id =>"2",:lga =>"Madagali"}, 
	{:state_id =>"2",:lga =>"Maiha"}, 
	{:state_id =>"2",:lga =>"Mayo-Belwa"}, 
	{:state_id =>"2",:lga =>"Michika"}, 
	{:state_id =>"2",:lga =>"Mubi North"}, 
	{:state_id =>"2",:lga =>"Mubi South"}, 
	{:state_id =>"2",:lga =>"Numan"}, 
	{:state_id =>"2",:lga =>"Shelleng"}, 
	{:state_id =>"2",:lga =>"Song"}, 
	{:state_id =>"2",:lga =>"Toungo"}, 
	{:state_id =>"2",:lga =>"Yola North"}, 
	{:state_id =>"2",:lga =>"Yola South"}, 
	{:state_id =>"3",:lga =>"Abak"}, 
	{:state_id =>"3",:lga =>"Eastern Obolo"}, 
	{:state_id =>"3",:lga =>"Eket"}, 
	{:state_id =>"3",:lga =>"Esit Eket"}, 
	{:state_id =>"3",:lga =>"Essien Udim"}, 
	{:state_id =>"3",:lga =>"Etim Ekpo"}, 
	{:state_id =>"3",:lga =>"Etinan"}, 
	{:state_id =>"3",:lga =>"Ibeno"}, 
	{:state_id =>"3",:lga =>"Ibesikpo Asutan"}, 
	{:state_id =>"3",:lga =>"Ibiono Ibom"}, 
	{:state_id =>"3",:lga =>"Ika"}, 
	{:state_id =>"3",:lga =>"Ikono"}, 
	{:state_id =>"3",:lga =>"Ikot Abasi"}, 
	{:state_id =>"3",:lga =>"Ikot Ekpene"}, 
	{:state_id =>"3",:lga =>"Ini"}, 
	{:state_id =>"3",:lga =>"Itu"}, 
	{:state_id =>"3",:lga =>"Mbo"},
	 {:state_id =>"3",:lga =>"Mkpat Enin"}, 
	 {:state_id =>"3",:lga =>"Nsit Atai"}, 
	 {:state_id =>"3",:lga =>"Nsit Ibom"}, 
	 {:state_id =>"3",:lga =>"Nsit Ubium"}, 
	 {:state_id =>"3",:lga =>"Obot Akara"}, 
	 {:state_id =>"3",:lga =>"Okobo"}, 
	 {:state_id =>"3",:lga =>"Onna"}, 
	 {:state_id =>"3",:lga =>"Oron"}, 
	 {:state_id =>"3",:lga =>"Oruk Anam"}, 
	 {:state_id =>"3",:lga =>"Udung Uko"}, 
	 {:state_id =>"3",:lga =>"Ukanafun"}, 
	 {:state_id =>"3",:lga =>"Uruan"}, 
	 {:state_id =>"3",:lga =>"Urue-Offong Oruko"},
	 {:state_id =>"3",:lga =>"Uyo"}, 
	 {:state_id =>"4",:lga =>"Aguata"}, 
	 {:state_id =>"4",:lga =>"Anambra East"}, 
	 {:state_id =>"4",:lga =>"Anambra West"}, 
	 {:state_id =>"4",:lga =>"Anaocha"}, 
	 {:state_id =>"4",:lga =>"Awka North "}, 
	 {:state_id =>"4",:lga =>"Awka South"}, 
	 {:state_id =>"4",:lga =>"Ayamelum"}, 
	 {:state_id =>"4",:lga =>"Dunukofia"}, 
	 {:state_id =>"4",:lga =>"Ekwusigo"}, 
	 {:state_id =>"4",:lga =>"Idemili North"}, 
	 {:state_id =>"4",:lga =>"Idemili south"}, 
	 {:state_id =>"4",:lga =>"Ihiala"}, 
	 {:state_id =>"4",:lga =>"Njikoka"}, 
	 {:state_id =>"4",:lga =>"Nnewi North"}, 
	 {:state_id =>"4",:lga =>"Nnewi South"}, 
	 {:state_id =>"4",:lga =>"Ogbaru4"}, 
	 {:state_id =>"4",:lga =>"Onitsha North"}, 
	 {:state_id =>"4",:lga =>"Onitsha South"}, 
	 {:state_id =>"4",:lga =>"Orumba North"}, 
	 {:state_id =>"4",:lga =>"Orumba South"}, 
	 {:state_id =>"4",:lga =>"Oyi"}, 
	 {:state_id =>"5",:lga =>"Alkaleri"}, 
	{:state_id =>"5",:lga =>"Bauchi"}, 
	{:state_id =>"5",:lga =>"Bogoro"}, 
	{:state_id =>"5",:lga =>"damban"}, 
	{:state_id =>"5",:lga =>"Darazo"}, 
	{:state_id =>"5",:lga =>"Dass"}, 
	{:state_id =>"5",:lga =>"Ganjuwa"}, 
	{:state_id =>"5",:lga =>"Giade"}, 
	{:state_id =>"5",:lga =>"Itas Gadau"}, 
	{:state_id =>"5",:lga =>"Jama'are"}, 
	{:state_id =>"5",:lga =>"Katagum"}, 
	{:state_id =>"5",:lga =>"Kirfi"}, 
	{:state_id =>"5",:lga =>"Misau"}, 
	{:state_id =>"5",:lga =>"Ningi"}, 
	{:state_id =>"5",:lga =>"Shira"}, 
	{:state_id =>"5",:lga =>"Tafawa-Balewa"}, 
	{:state_id =>"5",:lga =>"Toro"}, 
	{:state_id =>"5",:lga =>"Warji"}, 
	{:state_id =>"5",:lga =>"Zaki"}, 
	{:state_id =>"6",:lga =>"Brass"}, 
	{:state_id =>"6",:lga =>"Ekeremor"}, 
	{:state_id =>"6",:lga =>"Kolokuma Opokuma"}, 
	{:state_id =>"6",:lga =>"Nembe"}, 
	{:state_id =>"6",:lga =>"Ogbia"}, 
	{:state_id =>"6",:lga =>"Sagbama"}, 
	{:state_id =>"6",:lga =>"Southern Jaw"}, 
	{:state_id =>"6",:lga =>"Yenegoa"}, 
	{:state_id =>"7",:lga =>"Ado"}, 
	{:state_id =>"7",:lga =>"Agatu"}, 
	{:state_id =>"7",:lga =>"Apa"}, 
	{:state_id =>"7",:lga =>"Buruku"}, 
	{:state_id =>"7",:lga =>"Gboko"}, 
	{:state_id =>"7",:lga =>"Guma"}, 
	{:state_id =>"7",:lga =>"Gwer East"}, 
	{:state_id =>"7",:lga =>"Gwer West"}, 
	{:state_id =>"7",:lga =>"Katsina-Ala"}, 
	{:state_id =>"7",:lga =>"Konshisha"}, 
	{:state_id =>"7",:lga =>"Kwande"}, 
	{:state_id =>"7",:lga =>"Logo"}, 
	{:state_id =>"7",:lga =>"Makurdi"}, 
	{:state_id =>"7",:lga =>"Obi"}, 
	{:state_id =>"7",:lga =>"Ogbadibo"}, 
	{:state_id =>"7",:lga =>"Oju"}, 
	{:state_id =>"7",:lga =>"Okpokwu"}, 
	{:state_id =>"7",:lga =>"Ohimini"}, 
	{:state_id =>"7",:lga =>"Oturkpo"}, 
	{:state_id =>"7",:lga =>"Tarka"}, 
	{:state_id =>"7",:lga =>"Ukum"}, 
	{:state_id =>"7",:lga =>"Ushongo"}, 
	{:state_id =>"7",:lga =>"Vandeikya"}, 
	{:state_id =>"8",:lga =>"Abadam"}, 
	{:state_id =>"8",:lga =>"Askira Uba"}, 
	{:state_id =>"8",:lga =>"Bama"}, 
	{:state_id =>"8",:lga =>"Bayo"}, 
	{:state_id =>"8",:lga =>"Biu"}, 
	{:state_id =>"8",:lga =>"Chibok"}, 
	{:state_id =>"8",:lga =>"Damboa"}, 
	{:state_id =>"8",:lga =>"Dikwa"}, 
	{:state_id =>"8",:lga =>"Gubio"}, 
	{:state_id =>"8",:lga =>"Guzamala"}, 
	{:state_id =>"8",:lga =>"Gwoza"}, 
	{:state_id =>"8",:lga =>"Hawul"}, 
	{:state_id =>"8",:lga =>"Jere"}, 
	{:state_id =>"8",:lga =>"Kaga"}, 
	{:state_id =>"8",:lga =>"Kala Balge"}, 
	{:state_id =>"8",:lga =>"Konduga"}, 
	{:state_id =>"8",:lga =>"Kukawa"}, 
	{:state_id =>"8",:lga =>"Kwaya Kusar"}, 
	{:state_id =>"8",:lga =>"Mafa"}, 
	{:state_id =>"8",:lga =>"Magumeri"}, 
	{:state_id =>"8",:lga =>"Maiduguri"}, 
	{:state_id =>"8",:lga =>"Marte"}, 
	{:state_id =>"8",:lga =>"Mobbar"}, 
	{:state_id =>"8",:lga =>"Monguno"}, 
	{:state_id =>"8",:lga =>"Ngala"}, 
	{:state_id =>"8",:lga =>"Nganzai"}, 
	{:state_id =>"8",:lga =>"Shani"}, 
	{:state_id =>"9",:lga =>"Akpabuyo"}, 
	{:state_id =>"9",:lga =>"Odukpani"}, 
	{:state_id =>"9",:lga =>"Akamkpa "}, 
	{:state_id =>"9",:lga =>"Biase"}, 
	{:state_id =>"9",:lga =>"Abi"}, 
	{:state_id =>"9",:lga =>"Ikom"}, 
	{:state_id =>"9",:lga =>"Yarkur"}, 
	{:state_id =>"9",:lga =>"Odubra"}, 
	{:state_id =>"9",:lga =>"Boki"}, 
	{:state_id =>"9",:lga =>"Ogoja"}, 
	{:state_id =>"9",:lga =>"Yala"}, 
	{:state_id =>"9",:lga =>"Obanliku"}, 
	{:state_id =>"9",:lga =>"Obudu"}, 
	{:state_id =>"9",:lga =>"Calabar South"}, 
	{:state_id =>"9",:lga =>"Etung"}, 
	{:state_id =>"9",:lga =>"Bekwara"}, 
	{:state_id =>"9",:lga =>"Bakassi"}, 
	{:state_id =>"9",:lga =>"Calabar Municipality"}, 
	{:state_id =>"10",:lga =>"Oshimili"}, 
	{:state_id =>"10",:lga =>"Aniocha"}, 
	{:state_id =>"10",:lga =>"Aniocha South"}, 
	{:state_id =>"10",:lga =>"Ika South"}, 
	{:state_id =>"10",:lga =>"Ika North-East"}, 
	{:state_id =>"10",:lga =>"Ndokwa West"}, 
	{:state_id =>"10",:lga =>"Ndokwa East"}, 
	{:state_id =>"10",:lga =>"Isoko south"}, 
	{:state_id =>"10",:lga =>"Isoko North"}, 
	{:state_id =>"10",:lga =>"Bomadi"}, 
	{:state_id =>"10",:lga =>"Burutu"}, 
	{:state_id =>"10",:lga =>"Ughelli South"}, 
	{:state_id =>"10",:lga =>"Ughelli North"}, 
	{:state_id =>"10",:lga =>"Ethiope West"}, 
	{:state_id =>"10",:lga =>"Ethiope East"}, 
	{:state_id =>"10",:lga =>"Sapele"}, 
	{:state_id =>"10",:lga =>"Okpe"}, 
	{:state_id =>"10",:lga =>"Warri North"}, 
	{:state_id =>"10",:lga =>"Warri South"}, 
	{:state_id =>"10",:lga =>"Uvwie"}, 
	{:state_id =>"10",:lga =>"Udu"}, 
	{:state_id =>"10",:lga =>"Warri Central "}, 
	{:state_id =>"10",:lga =>"Ukwani"}, 
	{:state_id =>"10",:lga =>"Oshimili North"}, 
	{:state_id =>"10",:lga =>"Patani"}, 
	{:state_id =>"11",:lga =>"Afikpo South"}, 
	{:state_id =>"11",:lga =>"Afikpo North"}, 
	{:state_id =>"11",:lga =>"Onicha"}, 
	{:state_id =>"11",:lga =>"Ohaozara"}, 
	{:state_id =>"11",:lga =>"Abakaliki"}, 
	{:state_id =>"11",:lga =>"Ishielu"}, 
	{:state_id =>"11",:lga =>"lkwo"}, 
	{:state_id =>"11",:lga =>"Ezza"}, 
	{:state_id =>"11",:lga =>"Ezza South"}, 
	{:state_id =>"11",:lga =>"Ohaukwu"}, 
	{:state_id =>"11",:lga =>"Ebonyi"}, 
	{:state_id =>"11",:lga =>"Ivo"}, 
	{:state_id =>"12",:lga =>"Esan North-East"}, 
	{:state_id =>"12",:lga =>"Esan Central"}, 
	{:state_id =>"12",:lga =>"Esan West"}, 
	{:state_id =>"12",:lga =>"Egor"}, 
	{:state_id =>"12",:lga =>"Ukpoba"}, 
	{:state_id =>"12",:lga =>"Central"}, 
	{:state_id =>"12",:lga =>"Etsako Central"}, 
	{:state_id =>"12",:lga =>"Igueben"}, 
	{:state_id =>"12",:lga =>"Oredo"}, 
	{:state_id =>"12",:lga =>"Ovia South West"}, 
	{:state_id =>"12",:lga =>"Ovia South-East"}, 
	{:state_id =>"12",:lga =>"Orhionwon"}, 
	{:state_id =>"12",:lga =>"Uhunmwonde"}, 
	{:state_id =>"12",:lga =>"Etsako East"}, 
	{:state_id =>"12",:lga =>"Esan South-East"}, 
	{:state_id =>"13",:lga =>"Ado"}, 
	{:state_id =>"13",:lga =>"Ekiti-East"}, 
	{:state_id =>"13",:lga =>"Ekiti-West"}, 
	{:state_id =>"13",:lga =>"Emure Ise Orun"}, 
	{:state_id =>"13",:lga =>"Ekiti South-West"}, 
	{:state_id =>"13",:lga =>"Ikare"}, 
	{:state_id =>"13",:lga =>"Irepodun"}, 
	{:state_id =>"13",:lga =>"Ijero"}, 
	{:state_id =>"13",:lga =>"Ido Osi"}, 
	{:state_id =>"13",:lga =>"Oye"}, 
	{:state_id =>"14",:lga =>"Ikole"}, 
	{:state_id =>"14",:lga =>"Moba"}, 
	{:state_id =>"14",:lga =>"Gbonyin"}, 
	{:state_id =>"14",:lga =>"Efon"}, 
	{:state_id =>"14",:lga =>"Ise Orun"}, 
	{:state_id =>"14",:lga =>"Ilejemeje"}, 
	{:state_id =>"14",:lga =>"Enugu South"}, 
	{:state_id =>"14",:lga =>"Igbo-Eze South"}, 
	{:state_id =>"14",:lga =>"Enugu North"}, 
	{:state_id =>"14",:lga =>"Nkanu"}, 
	{:state_id =>"14",:lga =>"Udi Agwu"}, 
	{:state_id =>"14",:lga =>"Oji-River"}, 
	{:state_id =>"14",:lga =>"Ezeagu"}, 
	{:state_id =>"14",:lga =>"IgboEze North"}, 
	{:state_id =>"14",:lga =>"Isi-Uzo"}, 
	{:state_id =>"14",:lga =>"Nsukka"}, 
	{:state_id =>"14",:lga =>"Igbo-Ekiti"}, 
	{:state_id =>"14",:lga =>"Uzo-Uwani"}, 
	{:state_id =>"14",:lga =>"Enugu East"}, 
	{:state_id =>"14",:lga =>"Aninri"}, 
	{:state_id =>"14",:lga =>"Nkanu East"}, 
	{:state_id =>"14",:lga =>"Udenu"}, 
	{:state_id =>"16",:lga =>"Akko"}, 
	{:state_id =>"16",:lga =>"Balanga"}, 
	{:state_id =>"16",:lga =>"Billiri"}, 
	{:state_id =>"16",:lga =>"Dukku"}, 
	{:state_id =>"16",:lga =>"Kaltungo"}, 
	{:state_id =>"16",:lga =>"Kwami"}, 
	{:state_id =>"16",:lga =>"Shomgom"}, 
	{:state_id =>"16",:lga =>"Funakaye"}, 
	{:state_id =>"16",:lga =>"Gombe"}, 
	{:state_id =>"16",:lga =>"Nafada Bajoga"}, 
	{:state_id =>"15",:lga =>""}, 
	{:state_id =>"15",:lga =>"Gwagwalada"}, 
	{:state_id =>"15",:lga =>"Kuje"}, 
	{:state_id =>"15",:lga =>" Abaji "}, 
	{:state_id =>"15",:lga =>"Abuja Municipal"}, 
	{:state_id =>"15",:lga =>"Bwari"}, 
	{:state_id =>"15",:lga =>"Kwali"}, 
	{:state_id =>"17",:lga =>"Aboh-Mbaise"}, 
	{:state_id =>"17",:lga =>"Ahiazu-Mbaise"}, 
	{:state_id =>"17",:lga =>"Ehime-Mbano"}, 
	{:state_id =>"17",:lga =>"Ezinihitte"}, 
	{:state_id =>"17",:lga =>"Ideato North"}, 
	{:state_id =>"17",:lga =>"Ideato South"}, 
	{:state_id =>"17",:lga =>"Ihitte Uboma"}, 
	{:state_id =>"17",:lga =>"Ikeduru"}, 
	{:state_id =>"17",:lga =>"Isiala Mbano"}, 
	{:state_id =>"17",:lga =>"Isu"}, 
	{:state_id =>"17",:lga =>"Mbaitoli"}, 
	{:state_id =>"17",:lga =>"Ngor-Okpala"}, 
	{:state_id =>"17",:lga =>"Njaba"}, 
	{:state_id =>"17",:lga =>"Nwangele"}, 
	{:state_id =>"17",:lga =>"Nkwerre"}, 
	{:state_id =>"17",:lga =>"Obowo"}, 
	{:state_id =>"17",:lga =>"Oguta"}, 
	{:state_id =>"17",:lga =>"Ohaji Egbema"}, 
	{:state_id =>"17",:lga =>"Okigwe"}, 
	{:state_id =>"17",:lga =>"Orlu"}, 
	{:state_id =>"17",:lga =>"Orsu"}, 
	{:state_id =>"17",:lga =>"Oru East"}, 
	{:state_id =>"17",:lga =>"Oru West"}, 
	{:state_id =>"17",:lga =>"Owerri-Municipal"}, 
	{:state_id =>"17",:lga =>"Owerri North"}, 
	{:state_id =>"17",:lga =>"Owerri West"}, 
	{:state_id =>"18",:lga =>"Auyo"}, 
	{:state_id =>"18",:lga =>"Babura"}, 
	{:state_id =>"18",:lga =>"Birni Kudu"}, 
	{:state_id =>"18",:lga =>"Biriniwa"}, 
	{:state_id =>"18",:lga =>"Buji"}, 
	{:state_id =>"18",:lga =>"Dutse"}, 
	{:state_id =>"18",:lga =>"Gagarawa"}, 
	{:state_id =>"18",:lga =>"Garki "}, 
	{:state_id =>"18",:lga =>"Gumel"}, 
	{:state_id =>"18",:lga =>"Guri"}, 
	{:state_id =>"18",:lga =>"Gwaram"}, 
	{:state_id =>"18",:lga =>"Gwiwa"}, 
	{:state_id =>"18",:lga =>"Hadejia"}, 
	{:state_id =>"18",:lga =>"Jahun"}, 
	{:state_id =>"18",:lga =>"Kafin Hausa"}, 
	{:state_id =>"18",:lga =>"Kaugama Kazaure"}, 
	{:state_id =>"18",:lga =>"Kiri Kasamma"}, 
	{:state_id =>"18",:lga =>"Kiyawa"}, 
	{:state_id =>"18",:lga =>"Maigatari"}, 
	{:state_id =>"18",:lga =>"Malam Madori"}, 
	{:state_id =>"18",:lga =>"Miga"}, 
	{:state_id =>"18",:lga =>"Ringim"}, 
	{:state_id =>"18",:lga =>"Roni"}, 
	{:state_id =>"18",:lga =>"Sule-Tankarkar"}, 
	{:state_id =>"18",:lga =>"Taura"}, 
	{:state_id =>"18",:lga =>"Yankwashi"}, 
	{:state_id =>"19",:lga =>"Birni-Gwari"}, 
	{:state_id =>"19",:lga =>"Chikun"}, 
	{:state_id =>"19",:lga =>"Giwa"}, 
	{:state_id =>"19",:lga =>"Igabi"}, 
	{:state_id =>"19",:lga =>"Ikara"}, 
	{:state_id =>"19",:lga =>"jaba"}, 
	{:state_id =>"19",:lga =>"Jema'a"}, 
	{:state_id =>"19",:lga =>"Kachia"}, 
	{:state_id =>"19",:lga =>"Kaduna North"}, 
	{:state_id =>"19",:lga =>"Kaduna South"}, 
	{:state_id =>"19",:lga =>"Kagarko"}, 
	{:state_id =>"19",:lga =>"Kajuru"}, 
	{:state_id =>"19",:lga =>"Kaura"}, 
	{:state_id =>"19",:lga =>"Kauru"}, 
	{:state_id =>"19",:lga =>"Kubau"}, 
	{:state_id =>"19",:lga =>"Kudan"}, 
	{:state_id =>"19",:lga =>"Lere"}, 
	{:state_id =>"19",:lga =>"Makarfi"}, 
	{:state_id =>"19",:lga =>"Sabon-Gari"}, 
	{:state_id =>"19",:lga =>"Sanga"}, 
	{:state_id =>"19",:lga =>"Soba"}, 
	{:state_id =>"19",:lga =>"Zango-Kataf"}, 
	{:state_id =>"19",:lga =>"Zaria"}, 
	{:state_id =>"20",:lga =>"Ajingi"}, 
	{:state_id =>"20",:lga =>"Albasu"}, 
	{:state_id =>"20",:lga =>"Bagwai"}, 
	{:state_id =>"20",:lga =>"Bebeji"}, 
	{:state_id =>"20",:lga =>"Bichi"}, 
	{:state_id =>"20",:lga =>"Bunkure"}, 
	{:state_id =>"20",:lga =>"Dala"}, 
	{:state_id =>"20",:lga =>"Dambatta"}, 
	{:state_id =>"20",:lga =>"Dawakin Kudu"}, 
	{:state_id =>"20",:lga =>"Dawakin Tofa"}, 
	{:state_id =>"20",:lga =>"Doguwa"}, 
	{:state_id =>"20",:lga =>"Fagge"}, 
	{:state_id =>"20",:lga =>"Gabasawa"}, 
	{:state_id =>"20",:lga =>"Garko"}, 
	{:state_id =>"20",:lga =>"Garum"}, 
	{:state_id =>"20",:lga =>"Mallam"}, 
	{:state_id =>"20",:lga =>"Gaya"}, 
	{:state_id =>"20",:lga =>"Gezawa"}, 
	{:state_id =>"20",:lga =>"Gwale"}, 
	{:state_id =>"20",:lga =>"Gwarzo"}, 
	{:state_id =>"20",:lga =>"Kabo"}, 
	{:state_id =>"20",:lga =>"Kano Municipal"}, 
	{:state_id =>"20",:lga =>"Karaye"}, 
	{:state_id =>"20",:lga =>"Kibiya"}, 
	{:state_id =>"20",:lga =>"Kiru"}, 
	{:state_id =>"20",:lga =>"kumbotso"}, 
	{:state_id =>"20",:lga =>"Kunchi"}, 
	{:state_id =>"20",:lga =>"Kura"}, 
	{:state_id =>"20",:lga =>"Madobi"}, 
	{:state_id =>"20",:lga =>"Makoda"}, 
	{:state_id =>"20",:lga =>"Minjibir"}, 
	{:state_id =>"20",:lga =>"Nasarawa"}, 
	{:state_id =>"20",:lga =>"Rano"}, 
	{:state_id =>"20",:lga =>"Rimin Gado"}, 
	{:state_id =>"20",:lga =>"Rogo"}, 
	{:state_id =>"20",:lga =>"Shanono"}, 
	{:state_id =>"20",:lga =>"Sumaila"}, 
	{:state_id =>"20",:lga =>"Takali"}, 
	{:state_id =>"20",:lga =>"Tarauni"}, 
	{:state_id =>"20",:lga =>"Tofa "}, 
	{:state_id =>"20",:lga =>"Tsanyawa"}, 
	{:state_id =>"20",:lga =>"Tudun Wada"}, 
	{:state_id =>"20",:lga =>"Ungogo"}, 
	{:state_id =>"20",:lga =>"Warawa"}, 
	{:state_id =>"20",:lga =>"Wudil"}, 
	{:state_id =>"21",:lga =>"Bakori"}, 
	{:state_id =>"21",:lga =>"Batagarawa"}, 
	{:state_id =>"21",:lga =>"Batsari"}, 
	{:state_id =>"21",:lga =>"Baure"}, 
	{:state_id =>"21",:lga =>"Bindawa"}, 
	{:state_id =>"21",:lga =>"Charanchi"}, 
	{:state_id =>"21",:lga =>"Dandume"}, 
	{:state_id =>"21",:lga =>"Danja"}, 
	{:state_id =>"21",:lga =>"Dan Musa"}, 
	{:state_id =>"21",:lga =>"Daura"}, 
	{:state_id =>"21",:lga =>"Dutsi"}, 
	{:state_id =>"21",:lga =>"Dutsin-Ma"}, 
	{:state_id =>"21",:lga =>"Faskari"}, 
	{:state_id =>"21",:lga =>"Funtua"}, 
	{:state_id =>"21",:lga =>"Ingawa"}, 
	{:state_id =>"21",:lga =>"Jibia"}, 
	{:state_id =>"21",:lga =>"Kafur"}, 
	{:state_id =>"21",:lga =>"v"}, 
	{:state_id =>"21",:lga =>"Kaita"}, 
	{:state_id =>"21",:lga =>"Kankara"}, 
	{:state_id =>"21",:lga =>"Kankia"}, 
	{:state_id =>"21",:lga =>"Katsina"}, 
	{:state_id =>"21",:lga =>"Kurfi"}, 
	{:state_id =>"21",:lga =>"Kusada"}, 
	{:state_id =>"21",:lga =>"Mai'Adua"}, 
	{:state_id =>"21",:lga =>"Malumfashi "}, 
	{:state_id =>"21",:lga =>"Mani"}, 
	{:state_id =>"21",:lga =>"Mashi"}, 
	{:state_id =>"21",:lga =>"Matazuu"}, 
	{:state_id =>"21",:lga =>"Musawa"}, 
	{:state_id =>"21",:lga =>"Rimi"}, 
	{:state_id =>"21",:lga =>"Sabuwa"}, 
	{:state_id =>"21",:lga =>"Safana"}, 
	{:state_id =>"21",:lga =>"Matazuu"}, 
	{:state_id =>"21",:lga =>"Musawa"}, 
	{:state_id =>"21",:lga =>"Rimi"}, 
	{:state_id =>"21",:lga =>"Sabuwa"}, 
	{:state_id =>"21",:lga =>"Safana"}, 
	{:state_id =>"21",:lga =>"Sandamu"}, 
	{:state_id =>"21",:lga =>"Zango"}, 
	{:state_id =>"22",:lga =>"Aleiro"}, 
	{:state_id =>"22",:lga =>"Arewa-Dandi"}, 
	{:state_id =>"22",:lga =>"Argungu"}, 
	{:state_id =>"22",:lga =>"Augie"}, 
	{:state_id =>"22",:lga =>"Bagudo"}, 
	{:state_id =>"22",:lga =>"Birnin Kebbi"}, 
	{:state_id =>"22",:lga =>"Bunza"}, 
	{:state_id =>"22",:lga =>"Dandi"}, 
	{:state_id =>"22",:lga =>"Fakai"}, 
	{:state_id =>"22",:lga =>"Gwandu"}, 
	{:state_id =>"22",:lga =>"Jega"}, 
	{:state_id =>"22",:lga =>"Kalgo"}, 
	{:state_id =>"22",:lga =>"Koko\/Besse"}, 
	{:state_id =>"22",:lga =>"Maiyama"}, 
	{:state_id =>"22",:lga =>"Ngaski"}, 
	{:state_id =>"22",:lga =>"Sakaba"}, 
	{:state_id =>"22",:lga =>"Shanga"}, 
	{:state_id =>"22",:lga =>"Suru"}, 
	{:state_id =>"22",:lga =>"Wasagu\/Danko"}, 
	{:state_id =>"22",:lga =>"Yauri"}, 
	{:state_id =>"22",:lga =>"Zuru "}, 
	{:state_id =>"23",:lga =>"Adavi"}, 
	{:state_id =>"23",:lga =>"Ajaokuta"}, 
	{:state_id =>"23",:lga =>"Ankpa"}, 
	{:state_id =>"23",:lga =>"Bassa"}, 
	{:state_id =>"23",:lga =>"Dekina"}, 
	{:state_id =>"23",:lga =>"Ibaji"}, 
	{:state_id =>"23",:lga =>"Idah "}, 
	{:state_id =>"23",:lga =>"Igalamela-Odolu"}, 
	{:state_id =>"23",:lga =>"Ijumu"}, 
	{:state_id =>"23",:lga =>"Kabba\/Bunu"}, 
	{:state_id =>"23",:lga =>"Kogi"}, 
	{:state_id =>"23",:lga =>"Lokoja"}, 
	{:state_id =>"23",:lga =>"Mopa-Muro"}, 
	{:state_id =>"23",:lga =>"Ofu"}, 
	{:state_id =>"23",:lga =>"Ogori\/Mangongo"}, 
	{:state_id =>"23",:lga =>"Okehi"}, 
	{:state_id =>"23",:lga =>"Okene"}, 
	{:state_id =>"23",:lga =>"Olamabolo"}, 
	{:state_id =>"23",:lga =>"Omala"}, 
	{:state_id =>"23",:lga =>"Yagba East"}, 
	{:state_id =>"23",:lga =>"Yagba West"}, 
	{:state_id =>"24",:lga =>"Asa"}, 
	{:state_id =>"24",:lga =>"Baruten"}, 
	{:state_id =>"24",:lga =>"Edu"}, 
	{:state_id =>"24",:lga =>"Ekiti"}, 
	{:state_id =>"24",:lga =>"Ifelodun"}, 
	{:state_id =>"24",:lga =>"Ilorin East"}, 
	{:state_id =>"24",:lga =>"Ilorin West"}, 
	{:state_id =>"24",:lga =>"Irepodun"}, 
	{:state_id =>"24",:lga =>"Isin"}, 
	{:state_id =>"24",:lga =>"Kaiama"}, 
	{:state_id =>"24",:lga =>"Moro"}, 
	{:state_id =>"24",:lga =>"Offa"}, 
	{:state_id =>"24",:lga =>"Oke-Ero"}, 
	{:state_id =>"24",:lga =>"Oyun"}, 
	{:state_id =>"24",:lga =>"Pategi"}, 
	{:state_id =>"25",:lga =>"Agege"}, 
	{:state_id =>"25",:lga =>"Ajeromi-Ifelodun"}, 
	{:state_id =>"25",:lga =>"Alimosho"}, 
	{:state_id =>"25",:lga =>"Amuwo-Odofin"}, 
	{:state_id =>"25",:lga =>"Apapa"}, 
	{:state_id =>"25",:lga =>"Badagry"}, 
	{:state_id =>"25",:lga =>"Epe"}, 
	{:state_id =>"25",:lga =>"Eti-Osa"}, 
	{:state_id =>"25",:lga =>"Ibeju Lekki"}, 
	{:state_id =>"25",:lga =>"Ifako-Ijaye"}, 
	{:state_id =>"25",:lga =>"Ikeja"}, 
	{:state_id =>"25",:lga =>"Ikorodu"}, 
	{:state_id =>"25",:lga =>"Kosofe"}, 
	{:state_id =>"25",:lga =>"Lagos Island"}, 
	{:state_id =>"25",:lga =>"Lagos Mainland"}, 
	{:state_id =>"25",:lga =>"Mushin"}, 
	{:state_id =>"25",:lga =>"Ojo"}, 
	{:state_id =>"25",:lga =>"Oshodi-Isolo"}, 
	{:state_id =>"25",:lga =>"Shomolu"}, 
	{:state_id =>"25",:lga =>"Surulere"}, 
	{:state_id =>"26",:lga =>"Akwanga"}, 
	{:state_id =>"26",:lga =>"Awe"}, 
	{:state_id =>"26",:lga =>"Doma"}, 
	{:state_id =>"26",:lga =>"Karu"}, 
	{:state_id =>"26",:lga =>"Keana"}, 
	{:state_id =>"26",:lga =>"Keffi"}, 
	{:state_id =>"26",:lga =>"Kokona"}, 
	{:state_id =>"26",:lga =>"Lafia"}, 
	{:state_id =>"26",:lga =>"Nasarawa"}, 
	{:state_id =>"26",:lga =>"Nasarawa-Eggon"}, 
	{:state_id =>"26",:lga =>"Obi"}, 
	{:state_id =>"26",:lga =>"Toto "}, 
	{:state_id =>"26",:lga =>"Wamba"}, 
	{:state_id =>"27",:lga =>"Agaie"}, 
	{:state_id =>"27",:lga =>"Agwara"}, 
	{:state_id =>"27",:lga =>"Bida"}, 
	{:state_id =>"27",:lga =>"Borgu"}, 
	{:state_id =>"27",:lga =>"Bosso"}, 
	{:state_id =>"27",:lga =>"Chanchaga"}, 
	{:state_id =>"27",:lga =>"Edati"}, 
	{:state_id =>"27",:lga =>"Gbako"}, 
	{:state_id =>"27",:lga =>"Gurara"}, 
	{:state_id =>"27",:lga =>"Katcha"}, 
	{:state_id =>"27",:lga =>"Kontagora"}, 
	{:state_id =>"27",:lga =>"Lapai"}, 
	{:state_id =>"27",:lga =>"Lavun"}, 
	{:state_id =>"27",:lga =>"Magama"}, 
	{:state_id =>"27",:lga =>"Mariga"}, 
	{:state_id =>"27",:lga =>"Mashegu"}, 
	{:state_id =>"27",:lga =>"Mokwa"}, 
	{:state_id =>"27",:lga =>"Muya"}, 
	{:state_id =>"27",:lga =>"Pailoro"}, 
	{:state_id =>"27",:lga =>"Rafi"}, 
	{:state_id =>"27",:lga =>"Rijau"}, 
	{:state_id =>"27",:lga =>"Shiroro"}, 
	{:state_id =>"27",:lga =>"Suleja"}, 
	{:state_id =>"27",:lga =>"Tafa"}, 
	{:state_id =>"27",:lga =>"Wushishi"}, 
	{:state_id =>"28",:lga =>"Abeokuta North"}, 
	{:state_id =>"28",:lga =>"Abeokuta South"}, 
	{:state_id =>"28",:lga =>"Ado-Odo Ota"}, 
	{:state_id =>"28",:lga =>"Egbado North"}, 
	{:state_id =>"28",:lga =>"Egbado South"}, 
	{:state_id =>"28",:lga =>"Ewekoro"}, 
	{:state_id =>"28",:lga =>"Ifo"}, 
	{:state_id =>"28",:lga =>"Ijebu East"}, 
	{:state_id =>"28",:lga =>"Ijebu North"}, 
	{:state_id =>"28",:lga =>"Ijebu North East"}, 
	{:state_id =>"28",:lga =>"Ijebu Ode"}, 
	{:state_id =>"28",:lga =>"Ikenne"}, 
	{:state_id =>"28",:lga =>"Imeko-Afon"}, 
	{:state_id =>"28",:lga =>"Ipokia"}, 
	{:state_id =>"28",:lga =>"Obafemi-Owode"}, 
	{:state_id =>"28",:lga =>"Ogun Waterside"}, 
	{:state_id =>"28",:lga =>"Odeda"}, 
	{:state_id =>"28",:lga =>"Odogbolu"}, 
	{:state_id =>"28",:lga =>"Remo North"}, 
	{:state_id =>"28",:lga =>"Shagamu"}, 
	{:state_id =>"29",:lga =>"Akoko North East"}, 
	{:state_id =>"29",:lga =>"Akoko North West"}, 
	{:state_id =>"29",:lga =>"Akoko South Akure East"}, 
	{:state_id =>"29",:lga =>"Akoko South West"}, 
	{:state_id =>"29",:lga =>"Akure North"}, 
	{:state_id =>"29",:lga =>"Akure South"}, 
	{:state_id =>"29",:lga =>"Ese-Odo"}, 
	{:state_id =>"29",:lga =>"Idanre"}, 
	{:state_id =>"29",:lga =>"Ifedore"}, 
	{:state_id =>"29",:lga =>"Ilaje"}, 
	{:state_id =>"29",:lga =>"Ile-Oluji"}, 
	{:state_id =>"29",:lga =>"Okeigbo"}, 
	{:state_id =>"29",:lga =>"Irele"}, 
	{:state_id =>"29",:lga =>"Odigbo"}, 
	{:state_id =>"29",:lga =>"Okitipupa"}, 
	{:state_id =>"29",:lga =>"Ondo East"}, 
	{:state_id =>"29",:lga =>"Ondo West"}, 
	{:state_id =>"29",:lga =>"Ose"}, 
	{:state_id =>"29",:lga =>"Owo"}, 
	{:state_id =>"30",:lga =>"Aiyedade"}, 
	{:state_id =>"30",:lga =>""}, 
	{:state_id =>"30",:lga =>"Aiyedire"}, 
	{:state_id =>"30",:lga =>"Atakumosa East"}, 
	{:state_id =>"30",:lga =>"Atakumosa West"}, 
	{:state_id =>"30",:lga =>"Boluwaduro"}, 
	{:state_id =>"30",:lga =>"Boripe"}, 
	{:state_id =>"30",:lga =>"Ede North"}, 
	{:state_id =>"30",:lga =>"Ede South"}, 
	{:state_id =>"30",:lga =>"Egbedore"}, 
	{:state_id =>"30",:lga =>"Ejigbo"}, 
	{:state_id =>"30",:lga =>"Ife Central"}, 
	{:state_id =>"30",:lga =>"Ife East"}, 
	{:state_id =>"30",:lga =>"Ife North"}, 
	{:state_id =>"30",:lga =>"Ife South"}, 
	{:state_id =>"30",:lga =>"Ifedayo"}, 
	{:state_id =>"30",:lga =>"Ila"}, 
	{:state_id =>"30",:lga =>"Ilesha East"}, 
	{:state_id =>"30",:lga =>"Ilesha West"}, 
	{:state_id =>"30",:lga =>"Irepodun"}, 
	{:state_id =>"30",:lga =>"Irewole"}, 
	{:state_id =>"30",:lga =>"Isokan"}, 
	{:state_id =>"30",:lga =>"Iwo"}, 
	{:state_id =>"30",:lga =>"Obokun"}, 
	{:state_id =>"30",:lga =>"Odo-Otin"}, 
	{:state_id =>"30",:lga =>"Ola-Oluwa"}, 
	{:state_id =>"30",:lga =>"Olorunda"}, 
	{:state_id =>"30",:lga =>"Oriade"}, 
	{:state_id =>"30",:lga =>"Orolu"}, 
	{:state_id =>"30",:lga =>"Osogbo"}, 
	{:state_id =>"31",:lga =>"Afijio"}, 
	{:state_id =>"31",:lga =>"Akinyele"}, 
	{:state_id =>"31",:lga =>"Atiba"}, 
	{:state_id =>"31",:lga =>"Atigbo"}, 
	{:state_id =>"31",:lga =>"Egbeda"}, 
	{:state_id =>"31",:lga =>"Ibadan Central"}, 
	{:state_id =>"31",:lga =>"Ibadan North"}, 
	{:state_id =>"31",:lga =>"Ibadan North West"}, 
	{:state_id =>"31",:lga =>"Ibadan South East"}, 
	{:state_id =>"31",:lga =>"Ibadan South West"}, 
	{:state_id =>"31",:lga =>"Ibarapa Central"}, 
	{:state_id =>"31",:lga =>"Ibarapa East"}, 
	{:state_id =>"31",:lga =>"Ibarapa North"}, 
	{:state_id =>"31",:lga =>"Ido"}, 
	{:state_id =>"31",:lga =>"Irepo"}, 
	{:state_id =>"31",:lga =>"Iseyin"}, 
	{:state_id =>"31",:lga =>"Itesiwaju"}, 
	{:state_id =>"31",:lga =>"Iwajowa"}, 
	{:state_id =>"31",:lga =>"Kajola"}, 
	{:state_id =>"31",:lga =>"Lagelu Ogbomosho North"}, 
	{:state_id =>"31",:lga =>"Ogbmosho South"}, 
	{:state_id =>"31",:lga =>"Ogo Oluwa"}, 
	{:state_id =>"31",:lga =>"Olorunsogo"}, 
	{:state_id =>"31",:lga =>"Oluyole"}, 
	{:state_id =>"31",:lga =>"Ona-Ara"}, 
	{:state_id =>"31",:lga =>"Orelope"}, 
	{:state_id =>"31",:lga =>"Ori Ire"}, 
	{:state_id =>"31",:lga =>"Oyo East"}, 
	{:state_id =>"31",:lga =>"Oyo West"}, 
	{:state_id =>"31",:lga =>"Saki East"}, 
	{:state_id =>"31",:lga =>"Saki West"}, 
	{:state_id =>"31",:lga =>"Surulere"}, 
	{:state_id =>"32",:lga =>"Barikin Ladi"}, 
	{:state_id =>"32",:lga =>"Bassa"}, 
	{:state_id =>"32",:lga =>"Bokkos"}, 
	{:state_id =>"32",:lga =>"Jos East"}, 
	{:state_id =>"32",:lga =>"Jos North"}, 
	{:state_id =>"32",:lga =>"Jos South"}, 
	{:state_id =>"32",:lga =>"Kanam"}, 
	{:state_id =>"32",:lga =>"Kanke"}, 
	{:state_id =>"32",:lga =>"Langtang North"}, 
	{:state_id =>"32",:lga =>"Langtang South32"}, 
	{:state_id =>"32",:lga =>"Mangu"}, 
	{:state_id =>"32",:lga =>"Mikang"}, 
	{:state_id =>"32",:lga =>"Pankshin"}, 
	{:state_id =>"32",:lga =>"Qua'an Pan"}, 
	{:state_id =>"32",:lga =>"Riyom"}, 
	{:state_id =>"32",:lga =>"Shendam"}, 
	{:state_id =>"32",:lga =>"Wase"}, 
	{:state_id =>"33",:lga =>"Abua Odual"}, 
	{:state_id =>"33",:lga =>"Ahoada East"}, 
	{:state_id =>"33",:lga =>"Ahoada West"}, 
	{:state_id =>"33",:lga =>"Akuku Toru"}, 
	{:state_id =>"33",:lga =>"Andoni"}, 
	{:state_id =>"33",:lga =>"Asari-Toru"}, 
	{:state_id =>"33",:lga =>"Bonny"}, 
	{:state_id =>"33",:lga =>"Degema"}, 
	{:state_id =>"33",:lga =>"Emohua"}, 
	{:state_id =>"33",:lga =>"Eleme"}, 
	{:state_id =>"33",:lga =>"Gokana"}, 
	{:state_id =>"33",:lga =>"Ikwerre"}, 
	{:state_id =>"33",:lga =>"Khana"}, 
	{:state_id =>"33",:lga =>"Obia Akpor"}, 
	{:state_id =>"33",:lga =>"Ogba Egbema Ndoni"}, 
	{:state_id =>"33",:lga =>"Ogu Bolo"}, 
	{:state_id =>"33",:lga =>"Okrika"}, 
	{:state_id =>"33",:lga =>"Omumma"}, 
	{:state_id =>"33",:lga =>"Opobo Nkoro"}, 
	{:state_id =>"33",:lga =>"Oyigbo"}, 
	{:state_id =>"33",:lga =>"Port-Harcourt"}, 
	{:state_id =>"33",:lga =>"Tai"}, 
	{:state_id =>"34",:lga =>"Binji"}, 
	{:state_id =>"34",:lga =>"Bodinga"}, 
	{:state_id =>"34",:lga =>"Dange-shnsi"}, 
	{:state_id =>"34",:lga =>"Gada"}, 
	{:state_id =>"34",:lga =>"Goronyo"}, 
	{:state_id =>"34",:lga =>"Gudu"}, 
	{:state_id =>"34",:lga =>"Gawabawa"}, 
	{:state_id =>"34",:lga =>"Illela"}, 
	{:state_id =>"34",:lga =>"Isa"}, 
	{:state_id =>"34",:lga =>"Kware"}, 
	{:state_id =>"34",:lga =>"kebbe"}, 
	{:state_id =>"34",:lga =>"Rabah"}, 
	{:state_id =>"34",:lga =>"Sabon birni"}, 
	{:state_id =>"34",:lga =>"Shagari "}, 
	{:state_id =>"34",:lga =>"Silame"}, 
	{:state_id =>"34",:lga =>"Sokoto North"}, 
	{:state_id =>"34",:lga =>"Sokoto South"}, 
	{:state_id =>"34",:lga =>"Tambuwal"}, 
	{:state_id =>"34",:lga =>"Tqngaza"}, 
	{:state_id =>"34",:lga =>"Tureta"}, 
	{:state_id =>"34",:lga =>"Wamako"}, 
	{:state_id =>"34",:lga =>"Wurno"}, 
	{:state_id =>"35",:lga =>"Ardo-kola"}, 
	{:state_id =>"35",:lga =>"Bali"}, 
	{:state_id =>"35",:lga =>"Donga"}, 
	{:state_id =>"35",:lga =>"Gashaka"}, 
	{:state_id =>"35",:lga =>"Cassol"}, 
	{:state_id =>"35",:lga =>"Ibi"}, 
	{:state_id =>"35",:lga =>"Jalingo"},
	 {:state_id =>"35",:lga =>"Karin-Lamido"}, 
	 {:state_id =>"35",:lga =>"Kurmi"}, 
	 {:state_id =>"35",:lga =>"Lau"}, 
	 {:state_id =>"35",:lga =>"Sardauna"}, 
	 {:state_id =>"35",:lga =>"Takum"}, 
	 {:state_id =>"35",:lga =>"Ussa"}, 
	 {:state_id =>"35",:lga =>"Wukari"}, 
	 {:state_id =>"35",:lga =>"Yorro"}, 
	 {:state_id =>"35",:lga =>"Zing"}, 
	 {:state_id =>"36",:lga =>"Bade"}, 
	 {:state_id =>"36",:lga =>"Bursari"}, 
	 {:state_id =>"36",:lga =>"Damaturu"}, 
	 {:state_id =>"36",:lga =>"Fika"}, 
	 {:state_id =>"36",:lga =>"Fune"}, 
	 {:state_id =>"36",:lga =>"Geidam"}, 
	 {:state_id =>"36",:lga =>"Gujba"}, 
	 {:state_id =>"36",:lga =>"Gulani"}, 
	 {:state_id =>"36",:lga =>"Jakusko"}, 
	 {:state_id =>"36",:lga =>"Karasuwa"}, 
	 {:state_id =>"36",:lga =>"Karawa"}, 
	 {:state_id =>"36",:lga =>"Machina"}, 
	 {:state_id =>"36",:lga =>"Nangere"},
	  {:state_id =>"36",:lga =>"Nguru Potiskum"}, 
	  {:state_id =>"36",:lga =>"Tarmua"}, 
	  {:state_id =>"36",:lga =>"Yunusari"}, 
	  {:state_id =>"36",:lga =>"Yusufari"}, 
	  {:state_id =>"37",:lga =>"Anka"}, 
	  {:state_id =>"37",:lga =>"Bakura"}, 
	  {:state_id =>"37",:lga =>"Birnin Magaji"}, 
	  {:state_id =>"37",:lga =>"Bukkuyum"}, 
	  {:state_id =>"37",:lga =>"Bungudu"}, 
	  {:state_id =>"37",:lga =>"Gummi"}, 
	  {:state_id =>"37",:lga =>"Gusau"},
	  {:state_id =>"37",:lga =>"Kaura"}, 
	  {:state_id =>"37",:lga =>"Namoda"}, 
	  {:state_id =>"37",:lga =>"Maradun"}, 
	  {:state_id =>"37",:lga =>"Maru"}, 
	  {:state_id =>"37",:lga =>"Shinkafi"}, 
	  {:state_id =>"37",:lga =>"Talata Mafara"}, 
	  {:state_id =>"37",:lga =>"Tsafe"}, 
	  {:state_id =>"37",:lga =>"Zurmi"}
	 ].each do |lga|
	 		LocalGovtArea.create(lga)
	 	end

	 	puts "#{'*'*(`tput cols`.to_i)}\nThe database has been populated!\n#{'*'*(`tput cols`.to_i)}"

  end

end
